kukhariev/node-uploadx

src/handlers/uploadx.ts, src/utils/primitives.ts
This reverts commit de15e0c331747f0d2106751a04ca03fecd3a3e79.
=> Revert "refactor: use signed upload_id (#29)"

src/handlers/base-handler.ts
Fix close the connection on Windows.
=> fix: add request errors listener

src/handlers/base-handler.ts
=> fix: import path

packages/core/src/handlers/base-handler.ts, packages/core/src/handlers/cors.ts, test/cors.spec.ts
Adds more options for managing cors requests.
```ts
const uploads = new Uploadx({ storage });
uploads.cors.allowedMethods = ['POST', 'PUT'];
uploads.cors.origin = 'example.com';
```
=> refactor(core): cors class

examples/node-http-server.js, packages/core/src/handlers/uploadx.ts, packages/core/src/storages/disk-storage.ts, packages/core/src/storages/file.ts, packages/gcs/src/gcs-storage.ts, packages/s3/src/s3-storage.ts, test/uploadx.spec.ts
example:
```js
const uploads = new Uploadx({ storage });
uploads.on('updated', file => console.log(' metadata updated: ', file));
```
=> fix: notify metadata changes

proto.md, test/uploadx.spec.ts
Support for these requests is present, but not yet fixed.
=> docs: add `get` and `patch` requests to proto.md

packages/core/src/handlers/base-handler.ts, packages/core/src/handlers/multipart.ts, packages/core/src/handlers/tus.ts, packages/core/src/handlers/uploadx.ts
```ts
const uploadx = new Uploadx({ storage });
uploadx.getUserId = (req, res: AuthResponse) => res.locals.user?.id;
app.use('/files', uploadx.handle);
```
=> fix(core): get user id from res.locals

packages/core/src/handlers/base-handler.ts, test/base-handler.spec.ts
Allows to disable some features.
```ts
// disable cors, delete file, change metadata
Uploadx.methods = ['post', 'put', 'options'];
app.use('/upload', uploadx(opts));
```
=> fix(core): adjustable set of handled http-methods

packages/core/src/storages/disk-storage.ts
Remove the almost useless "updated" field.
=> refactor: DiskListObject

examples/express.ts, packages/core/src/handlers/base-handler.ts, packages/core/src/handlers/tus.ts, packages/core/src/storages/disk-storage.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/errors.ts, packages/core/src/utils/http.ts, packages/core/src/utils/validator.ts, test/base-handler.spec.ts, test/disk-storage.spec.ts, test/validator.spec.ts
Adds more flexibility to customize error messages:
```ts
const storage = new DiskStorage({
validation: {
mime: { value: ['video/*'], response: [415, { message: 'video only' }] },
size: {
value: 500_000,
isValid(file) {
this.response = [
412,
{ message: `The file size(${file.size}) is larger than ${this.value as number} bytes` }
];
return file.size <= this.value;
}
},
mtime: {
isValid: file => !!file.metadata.lastModified,
response:  { statusCode: 403, body: 'Missing `lastModified` property' }
}
}
});
```
=> refactor(core): validator response

packages/core/src/storages/storage.ts
Now the expired file will always be re-uploaded from the beginning.
=> fix(storage): remove expired uploads

examples/express-basic.ts, packages/core/src/handlers/base-handler.ts, packages/core/src/handlers/multipart.ts, packages/core/src/handlers/tus.ts, packages/core/src/handlers/uploadx.ts, packages/core/src/storages/disk-storage.ts, packages/core/src/storages/file.ts, packages/core/src/storages/local-meta-storage.ts, packages/core/src/storages/meta-storage.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/cache.ts, packages/core/src/utils/primitives.ts, packages/gcs/src/gcs-meta-storage.ts, packages/gcs/src/gcs-storage.ts, packages/s3/src/s3-meta-storage.ts, packages/s3/src/s3-storage.ts, test/base-handler.spec.ts, test/disk-storage.spec.ts, test/gcs-storage.spec.ts, test/local-meta-storage.spec.ts, test/multipart.spec.ts, test/s3-storage.spec.ts, test/shared/testfile.ts, test/tus.spec.ts, test/uploadx.spec.ts, test/util.spec.ts
Also:
- The `filename` option no longer changes `upload_id` or meta filename.
- Added a fast check of the upload owner.
- Hashes memoization
=> refactor(core): updated upload id format 

README.md, examples/express.ts, jest.config.js, packages/core/src/handlers/base-handler.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/cache.ts, packages/gcs/src/gcs-storage.ts, packages/s3/src/s3-storage.ts, test/base-handler.spec.ts, test/uploadx.spec.ts
usage: 
```ts
app.all(
uploadx({
expiration: { maxAge: '1h', purgeInterval: '10min' },
userIdentifier: (req: express.Request & UserInfo) => req.user!.email + req.user!.id
})
);
```
=> feat: `userIdentifier` option

examples/express-basic.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/http.ts
Maybe fix https://github.com/Chocobozzz/PeerTube/issues/4990
=> refactor:  http/https protocol identification

packages/core/src/handlers/cors.ts, packages/core/src/handlers/tus.ts, packages/core/src/utils/http.ts, packages/core/src/utils/primitives.ts, test/util.spec.ts
Address https://github.com/Chocobozzz/PeerTube/issues/4819
=> fix: better handling multi-value headers

packages/core/src/utils/http.ts
=> refactor: protocol identification

packages/core/src/utils/primitives.ts, test/__snapshots__/disk-storage.spec.ts.snap, test/__snapshots__/gcs-storage.spec.ts.snap, test/__snapshots__/s3-storage.spec.ts.snap, test/shared/config.ts, test/util.spec.ts
use fnv1a 64bit for id segments
=> fix(core): reduce probability of id collisions

.github/workflows/test.yml, package.json, packages/core/package.json, packages/gcs/package.json, packages/node-uploadx/package.json, packages/s3/package.json
Node.js v14 is now the minimum required version
=> fix!: drop Node.js v12

packages/core/src/storages/disk-storage.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/errors.ts, packages/core/src/utils/index.ts, packages/core/src/utils/locker.ts, packages/gcs/src/gcs-storage.ts, packages/s3/src/s3-storage.ts, test/disk-storage.spec.ts
Prevent uploads from being accessed by multiple requests, which can potentially corrupt data.
=> feat(storage): lock uploads

README.md, examples/.env.example, examples/express-basic.ts, examples/express-s3.ts, examples/express-tus.ts, examples/express.ts, examples/fastify.ts, examples/package.json, packages/core/src/handlers/base-handler.ts, packages/core/src/storages/config.ts, packages/core/src/storages/disk-storage.ts, packages/core/src/storages/local-meta-storage.ts, packages/core/src/storages/meta-storage.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/logger.ts, packages/gcs/src/gcs-storage.ts, packages/s3/src/s3-storage.ts, test/shared/uploader.ts, test/storage.spec.ts, test/util.spec.ts, yarn.lock
- Built-in logger now support severity levels:
```ts
app.use(
'/files',
uploadx({
logLevel: <LogLevel>process.env.LOG_LEVEL || 'info'
})
);
```
- Added support for custom loggers:
```ts
const logger = someLoggerLib.createLogger({
level: process.env.LOG_LEVEL || 'info',
});
app.use(
'/upload',
uploadx({
logger: logger
})
);
```
=> feat: extended logging support

package.json, packages/core/package.json, yarn.lock
- remove unused `debug` package
- downgrade jest for ts-jest compatibility
=> chore: dev deps fixes

packages/core/src/handlers/base-handler.ts, packages/core/src/storages/storage.ts, test/uploadx.spec.ts
=> fix: formatting response body

README.md, packages/core/src/handlers/base-handler.ts, packages/core/src/handlers/uploadx.ts, packages/core/src/storages/config.ts, packages/core/src/storages/file.ts, packages/core/src/storages/storage.ts, packages/core/src/utils/http.ts, packages/core/src/utils/primitives.ts, test/uploadx.spec.ts, test/util.spec.ts
usage example:
```ts
...
async function onUpdate({ name, metadata }: DiskFile) {
await VideoInfo.updateOne({ name }, metadata);
return metadata; // same as { body: metadata, statusCode: 200 };
}
const uploads = uploadx({
onCreate: async file => onCreate(file),
onUpdate: async file => onUpdate(file),
onComplete: async file => onComplete(file),
onDelete: async file => onDelete(file)
});
app.use('/upload', uploads);
...
```
=> feat: add `onCreate`, `onUpdate`, `onDelete` hooks

examples/express.ts, packages/core/src/handlers/base-handler.ts, packages/core/src/storages/storage.ts
Exclude the logger instance from the debugging log.
=> refactor(core): logging config

examples/server.js
Use environment variables to configure the demo server.
=> chore: update demo server

examples/.env.example, packages/core/src/utils/primitives.ts, packages/s3/src/s3-storage.ts
set environment variable `S3_DEBUG` to enable
=> fix(s3): disable S3Client logger

packages/s3/src/s3-storage.ts
types compatibility  with  aws-sdk-js-v3 3.428+
=> refactor(s3): stricter ACL type

packages/core/src/storages/disk-storage.ts
Preventing possible streams memory leaks
=> fix(disk): force streams to close

package-lock.json, packages/core/package.json, packages/core/src/utils/primitives.ts, test/util.spec.ts
and implement custom duration parsing
Fixes #684
=> fix: remove parse-duration dependency

packages/core/src/utils/errors.ts, test/__snapshots__/s3-storage.spec.ts.snap, test/s3-storage.spec.ts, test/shared/streams.ts, test/tus.spec.ts
Refactor `UploadxError` to extend the native `Error` class.
=> feat: refactor `UploadxError`
