- .eslintrc.js
- README.md
- examples/express-basic.ts
- examples/express-gcs.ts
- examples/express.ts
- examples/package.json
- packages/core/src/handlers/base-handler.ts
- packages/core/src/handlers/tus.ts
- packages/core/src/storages/file.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/errors.ts
- test/disk-storage.spec.ts
- test/uploadx.spec.ts
example:
```ts
const options = {
allowMIME: { value: ['video/*'], message: 'Only Video files is supported.', statusCode: 415 },
maxUploadSize: { value: '1GB', message: 'File is too big.', statusCode: 413 },
};
app.use('/files', uploadx(options);
```
> feat: allow customize validation errors

- examples/express.ts
- packages/core/src/handlers/base-handler.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/errors.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/validator.ts
- test/base-handler.spec.ts
- test/disk-storage.spec.ts
- test/gcs-storage.spec.ts
- test/s3-storage.spec.ts
- test/validator.spec.ts
Allows to tweak existing `size` and `mime` validators and add new ones.
```ts
const storage = new DiskStorage({
maxUploadSize: '1GB',
onComplete,
validation: {
mime: { value: ['video/*'], response: [415, { error: 'video only' }] },
channel: {
isValid: file => !!file.metadata.channel,
response: [403, { error: 'missing channel id' }]
}
}
});
const uploadx = new Uploadx({ storage });
```
> feat(core): customizable validators

- examples/express.ts
- packages/core/src/handlers/uploadx.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/errors.ts
- packages/core/src/utils/http.ts
- test/uploadx.spec.ts
Allows  to control the maximum size of the metadata, for example in case of large base64-encoded pictures in the metadata.
> fix: configurable metadata size limit

- packages/core/src/storages/disk-storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/s3/src/s3-storage.ts
Prevents a completed file from being reuploaded after it has been moved or deleted.
https://github.com/Chocobozzz/PeerTube/issues/3661#issuecomment-875224445
> fix: lock completed files

- README.md
- examples/express-s3.js
- examples/gcs-direct.ts
- packages/core/src/handlers/base-handler.ts
- packages/core/src/handlers/multipart.ts
- packages/core/src/handlers/tus.ts
- packages/core/src/handlers/uploadx.ts
- packages/core/src/storages/disk-storage.ts
- packages/core/src/storages/file.ts
- packages/core/src/storages/index.ts
- packages/core/src/storages/local-meta-storage.ts
- packages/core/src/storages/meta-storage.ts
- packages/core/src/storages/storage.ts
- packages/gcs/src/constants.ts
- packages/gcs/src/gcs-meta-storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/gcs/src/index.ts
- packages/s3/src/s3-meta-storage.ts
- packages/s3/src/s3-storage.ts
- test/disk-storage.spec.ts
- test/fixtures/uploader.ts
- test/gcs-storage.spec.ts
- test/local-meta-storage.spec.ts
- test/s3-storage.spec.ts
- test/tus.spec.ts
- test/uploadx.spec.ts
This PR adds:
- option for configuring metafile storage. Some examples:
```ts
// use a custom path for metafiles
const storage = new DiskStorage({
metaStorageConfig: {
directory: '/tmp/upload-metafiles',
prefix: '.',
suffix: '.json'
}
});
```
```ts
// use local metafiles while uploading to cloud
const storage = new GCStorage({
bucket: 'uploads',
metaStorageConfig: { directory: '/tmp/upload-metafiles' }
});
```
```ts
// use a separate bucket for metafiles
const storage = new GCStorage({
bucket: 'uploads',
metaStorageConfig: { bucket: 'upload-metafiles' }
});
```
- `metaStorage` option to use a custom metadata storage
- `saveMeta`, `getMeta`, `deleteMeta` methods for metafiles
> feat(storage): metastorage configuration

- packages/core/src/utils/cache.ts
- test/cache.spec.ts
If delete the download metafile, its contents may take a long time to be stored in the cache. This PR set cache TTL to 5 minutes.
Override example: 
```ts
const storage = new DiskStorage({ directory: 'uploads'});
storage.cache.maxAge = 40; 
```
> fix: expire cache entries

- README.md
- examples/express-basic.ts
- examples/express.ts
- packages/core/package.json
- packages/core/src/handlers/tus.ts
- packages/core/src/handlers/uploadx.ts
- packages/core/src/storages/disk-storage.ts
- packages/core/src/storages/file.ts
- packages/core/src/storages/local-meta-storage.ts
- packages/core/src/storages/meta-storage.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/primitives.ts
- packages/gcs/src/gcs-meta-storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/s3/src/s3-meta-storage.ts
- packages/s3/src/s3-storage.ts
- test/disk-storage.spec.ts
- yarn.lock
- automatic cleaning of abandoned and completed uploads.
```typescript
app.all(
'/upload',
uploadx.upload({
expiration: { maxAge: '6h', purgeInterval: '30min' }
}),
onComplete
);
```
- sends `Upload-Expires` headers to client
- sends `410 Gone` if the client tries to resume an expired upload
- `storage.purge(maxAge?: number | string, prefix?: string): Promise<PurgeList>` method to search for and delete upload files
> feat(storage): upload expiration

- packages/core/src/handlers/tus.ts
- packages/core/src/storages/file.ts
- test/tus.spec.ts
The header  `Upload-Metadata: 'name bmFtZS5leHQ=,is_ok'` must be parsed as
```ts
{ name: 'name.ext', is_ok: '' }
```
also kukhariev/ngx-uploadx#354
> fix(tus): support metadata empty values

- packages/gcs/src/constants.ts
- packages/gcs/src/gcs-config.ts
- packages/gcs/src/gcs-meta-storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/gcs/src/index.ts
Moved API urls to `GCSConfig` class static props.
> refactor(gcs): allow override api urls

- packages/core/src/utils/http.ts
- test/uploadx.spec.ts
Do not limit the size of the non-json  post request body
> fix: `post` request body size limit

- packages/core/src/storages/disk-storage.ts
- packages/core/src/storages/local-meta-storage.ts
- packages/core/src/storages/meta-storage.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/primitives.ts
- test/util.spec.ts
Check the upload activity when purging.
Each time the upload is accessed, the expiration is delayed.
To enable, set `expiration.rolling` to `true` .
```ts
const storage = new DiskStorage({
expiration: { maxAge: '1h', purgeInterval: '30min', rolling: true },
});
```
https://github.com/Chocobozzz/PeerTube/issues/4907
> feat: rolling expiration

- README.md
- examples/express-tus.ts
- packages/core/src/handlers/tus.ts
- packages/core/src/handlers/uploadx.ts
- packages/core/src/storages/disk-storage.ts
- packages/core/src/storages/file.ts
- packages/core/src/storages/storage.ts
- packages/core/src/utils/errors.ts
- packages/core/src/utils/fs.ts
- test/disk-storage.spec.ts
- test/shared/testfile.ts
- test/tus.spec.ts
- test/uploadx.spec.ts
- support tus checksum  extension
-  experimental support [Digest headers ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest)to verify data integrity of each chunk request.  460 status code will be returned if the checksums do not match.
```http
PUT http://example.com/upload?upload_id=471e97554f21dec3b8bb5d4602939c51
Content-Type: application/octet-stream
Content-Range: bytes 0-262143/2469036б
Digest: sha=gD5eezxkTfmNFCZ2SUA+ZjYcLyg=
Content-Length: 262144
[BYTES 0-262143]
```
closes #518
> feat(core): support chunk checksum

- packages/core/src/handlers/multipart.ts
- packages/core/src/storages/file.ts
- packages/core/src/utils/http.ts
- test/util.spec.ts
Support 'X-Forwarded-Host' header if express/fastify 'trust proxy' .
> refactor: host headers handling

- packages/core/src/utils/http.ts
undo #558 because `req.host` is deprecated in Express v4
> refactor: dot not use express v4 deprecated req.host

- packages/core/src/utils/http.ts
Undo #558 because `req.host` is deprecated in Express v4.
> refactor: dot not use req.host

- examples/express-basic.ts
- examples/express.ts
- packages/core/src/handlers/base-handler.ts
- packages/core/src/storages/config.ts
- packages/core/src/storages/disk-storage.ts
- packages/core/src/storages/meta-storage.ts
- packages/core/src/storages/storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/s3/src/s3-storage.ts
- test/shared/uploader.ts
- test/uploadx.spec.ts
- tsconfig.base.json
Added `onError` hook to options
```ts
app.use(
'/upload',
uploadx({
onError: ({ statusCode, body }) => {
const errors = [{ status: statusCode, title: body?.code, detail: body?.message }];
return {
statusCode,
headers: { 'Content-Type': 'application/vnd.api+json' },
body: { errors }
};
},
onComplete: file => {
console.log('File upload complete: ', file);
return file;
}
})
);
```
> feat(core): option to customize error responses

- examples/package.json
- examples/s3-direct.ts
- packages/core/src/handlers/uploadx.ts
- packages/core/src/utils/primitives.ts
- packages/s3/package.json
- packages/s3/src/s3-storage.ts
- test/s3-storage.spec.ts
- yarn.lock
- Added initial S3 multipart upload using presigned urls.  
Please note that this is an experimental feature and is currently not fully tested.
> feat(s3): `clientDirectUpload` option

- examples/express-gcs.ts
- packages/core/src/storages/disk-storage.ts
- packages/gcs/src/gcs-storage.ts
- packages/s3/src/s3-storage.ts
- test/s3-storage.spec.ts
Allows send patch request with empty body to complete/get presigned uploads
> refactor(s3): handle presigned uploads

- examples/.env.example
- examples/express-basic.ts
- examples/express-polling.ts
- examples/express-tus.ts
- examples/express.ts
- examples/fastify.ts
- examples/node-http-server.js
- examples/server.js
- examples/validation.ts
Support for the `UPLOAD_DIR` environment variable to set the upload directory in the examples.
> chore: env variable sets upload dir in examples

- packages/core/src/types/http.ts
The optional `req` is no longer needed in newer versions of NodeJS (v15.7.0+)
> fix(types): ServerResponse type
